import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../values/css/globals.css";
import { LayoutBaseModel } from "@/models";
import Providers from "./providers";
import styles from "./layout.module.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Layout: LayoutBaseModel = ({ children }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={styles.container}>
          <Providers>{children}</Providers>
        </div>
      </body>
    </html>
  );
};

export default Layout;
